services:
  app:
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init/pg_hba.conf:/docker-entrypoint-initdb.d/pg_hba.conf
    env_file:
      - .env
    command:
      - "postgres"
      - "-c"
      - "hba_file=/var/lib/postgresql/data/pg_hba.conf"
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
