# TYPE  DATABASE        USER            ADDRESS                 METHOD
# Allow connections from any IP address on the Docker networks using scram-sha-256
host    all             all             0.0.0.0/0               scram-sha-256
host    all             all             ::/0                    scram-sha-256

# Allow local connections (e.g., psql CLI within the container)
local   all             all                                     trust

